version: 2
jobs:
  build:
    docker:
      - image: seesharprun/content-generation-pandoc:0.1.0
    environment:
      MAJOR_VERSION: 4
      MINOR_VERSION: 2
      COURSE: 20532
      REVISION: D
    working_directory: ~/source/
    steps:
      - checkout
      - run:
          name: Test Pandoc
          command: pandoc -v
      - run:
          name: Test PDFLatex
          command: pdflatex -v
      - run:
          name: Update Environment Variable at Runtime
          command: |
            echo 'export VERSION_NUMBER=$MAJOR_VERSION.$MINOR_VERSION.$CIRCLE_BUILD_NUM' >> $BASH_ENV
            echo 'export COURSE_IDENTIFIER=$COURSE$REVISION' >> $BASH_ENV
            source $BASH_ENV
      - run:
          working_directory: ~/source/.build
          name: Install NPM Packages
          command: npm install  
      - save_cache:
          key: dependency-cache-{{ checksum "~/source/.build/package.json" }}
          paths:
            - ~/source/.build/node_modules
      - run:
          working_directory: ~/source/.build
          name: Build Lab Content
          command: node package.js --version $VERSION_NUMBER --course $COURSE_IDENTIFIER
      - store_artifacts:
          path: ~/source/.build/out
          destination: /
